services:
  - type: web
    name: popette-plant-app
    env: static
    buildCommand: npm install
    startCommand: npm start
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 