services:
  - type: web
    name: popette-plant-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
    buildFilter:
      paths:
        - package.json
        - server.js
        - "*.js"
        - "*.html"
        - "*.css" 